### ISSUE TITLE
Unexpected result invoking `context(...)` with duplicate keys

### ISSUE THREAD

**Issue by lzgabel** [nikku/feelin#89]
### Describe the Bug
From the description in the document：
https://docs.camunda.io/docs/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion/#contextentries

> It might override context entries if the keys are equal. The entries are overridden in the same order as the contexts in the given list.

* The result of evaluating the following expression does not match the expected result of FEEL:
```
context([{"key":"a", "value":1}, {"key":"a", "value":2}])  // null
```

### Steps to Reproduce

https://nikku.github.io/feel-playground/?e=%7E3YCAkIC5gICAgICAgICxG0qZWmqwek3NMmc3S9EN25NtVD8Uwxo8BCX4Ih8ZWjpt6nMX5YjbLDoY239%2FRUnQgA%3D%3D&c=%7B%0A++%0A%7D&t=expression&st=true

### Expected Behavior
```
context([{"key":"a", "value":1}, {"key":"a", "value":2}])  // {a: 2}
```

* The result of evaluating the expression in the `FEEL-Scala` Playground:
<img width="847" alt="image" src="https://github.com/user-attachments/assets/bd5e1889-479d-45eb-a4a7-97757b6cebac">

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
This is _won't fix_, since the spec is clear about this behavior: The result _must_ contain all specified entries, which is not the case when there is duplicate keys:

![image](https://github.com/user-attachments/assets/ccfe142e-3f27-461f-99a0-65e6c6f74a92)


See also [tck tests](https://github.com/dmn-tck/tck/blob/a967d577aafa2dd0e456084bf964d9e8fb6da0b5/TestCases/compliance-level-3/1145-feel-context-function/1145-feel-context-function-test-01.xml#L43), which asserts this.

**Comment by nikku** [comment]
I do have my own opinion here: The language should not be overly unforgiven, however this targets DMN FEEL as a foundation, not my own interpretation.

Consider to raise this with the [dmn-tck](https://github.com/dmn-tck/tck). Happy to adjust the behavior if we remove the offending test from the spec.
